#!/bin/sh
set -eu
cd "$(dirname "$0")/.."
out=${1:-docs/code.md}
{
    echo "# code"
    echo ""
    echo "generated by \`scripts/docs.sh\` from doc comments"
    for file in $(find pet -name '*.rs' -not -path '*/target/*' | sort); do
        printf '\n## %s\n' "$file"
        awk -f scripts/docs.awk "$file"
    done
} > "$out"
