name = "Cat"
color = "#f5c2e7"

[colors]
1 = "#f38ba8"
2 = "#89dceb"
3 = "#fab387"
4 = "#b4befe"

[clips.idle]
frame_ms = 400
sequence = [0, 0, 0, 0, 0, 1]
frames = [
'''
 /\_/\
( o.o )
 > ^1^^^0 <
''',
'''
 /\_/\
( -.- )
 > ^1^^^0 <
''',
]

[clips.happy]
frame_ms = 250
sequence = [0, 0, 0, 0, 0, 0, 1, 0, 1]
frames = [
'''
 /\_/\
( ^^.^^ )
 > ^1^^^0 <
''',
'''
 /\_/\
( ^^.^^ )
 > ^1^^^0 <

''',
]

[clips.sad]
frame_ms = 500
sequence = [0, 0, 0, 0, 0, 1]
frames = [
'''
 /\_/\
( ^2;^0_^2;^0 )
 > ^1^^^0 <
''',
'''
 /\_/\
( -_- )
 > ^1^^^0 <
''',
]

[clips.eat]
frame_ms = 300
sequence = [0, 1, 0, 1, 0, 1]
frames = [
'''
 /\_/\
( o.o )   ^3@
 > ^1^^^0 <
''',
'''
 /\_/\
( ^^o^^ )  ^3.:
 > ^1^^^0 <
''',
]

[clips.pet]
frame_ms = 300
sequence = [0, 1, 0, 1, 0, 1]
frames = [
'''
 /\_/\
( ^^.^^ )  ^1♥
 > ^1^^^0 <
''',
'''
 /\_/\    ^1♥
( ^^.^^ )
 > ^1^^^0 <
''',
]

[clips.play]
frame_ms = 250
sequence = [0, 1, 0, 1, 0, 1, 0, 1]
frames = [
'''
 /\_/\
( o.o )
 > ^1^^^0 <   ^2o
''',
'''
 /\_/\      ^2o
( O.O )
 > ^1^^^0 <

''',
]

[clips.sleep]
frame_ms = 700
frames = [
'''
 /\_/\   ^4z
( -.- )
 > ^1^^^0 <
''',
'''
 /\_/\    ^4Z
( -.- )  ^4z
 > ^1^^^0 <
''',
]
