species = "Bunny"
color = "#dcd0f5"

[colors]
1 = "#f38ba8"
2 = "#89dceb"
3 = "#fab387"
4 = "#89b4fa"
5 = "#a6e3a1"

[clips.idle]
frame_ms = 400
sequence = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2]
frames = [
'''
(\__/)
(='^1.^0'=)
(")_(")
''',
'''
(\__/)
(=-^1.^0-=)
(")_(")
''',
'''
(\__/)
(='^1.^0'=)
(")_(")

''',
]

[clips.happy]
frame_ms = 200
sequence = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1]
frames = [
'''
(\__/)
(=^^^1.^0^^=)
(")_(")
''',
'''
(\__/)
(=^^^1.^0^^=)
(")_(")

''',
]

[clips.sad]
frame_ms = 500
sequence = [0, 0, 0, 0, 0, 1]
frames = [
'''
(\__/)
(=^2;^0_^2;^0=)
(")_(")
''',
'''
(\__/)
(=-_-=)
(")_(")
''',
]

[clips.eat]
frame_ms = 300
sequence = [0, 1, 0, 1, 0, 1]
frames = [
'''
(\__/)
(='^1.^0'=)
(")_(")  ^3<=^5w
''',
'''
(\__/)
(=^^o^^=)
(")_(")   ^3=^5w
''',
]

[clips.pet]
frame_ms = 300
sequence = [0, 1, 0, 1, 0, 1]
frames = [
'''
(\__/)
(=^^^1.^0^^=)  ^1♥
(")_(")
''',
'''
(\__/)   ^1♥
(=^^^1.^0^^=)
(")_(")
''',
]

[clips.play]
frame_ms = 250
sequence = [0, 1, 0, 1, 0, 1, 0, 1]
frames = [
'''
(\__/)
(='^1.^0'=)
(")_(")   ^2o
''',
'''
(\__/)    ^2o
(=O^1.^0O=)
(")_(")

''',
]

[clips.sleep]
frame_ms = 700
frames = [
'''
(\__/) ^4z
(=-^1.^0-=)
(")_(")
''',
'''
(\__/)   ^4Z
(=-^1.^0-=) ^4z
(")_(")
''',
]
