# Based on a puppy by Joan G. Stark (jgs).
species = "Dog"
color = "#ebcfb2"

[colors]
1 = "#f38ba8"
2 = "#89dceb"
3 = "#fab387"
4 = "#b4befe"

[clips.idle]
frame_ms = 400
sequence = [0, 0, 0, 0, 0, 1]
frames = [
'''
  .-"-.
 /|6 6|\
{/(_0_)\}
 _/ ^^ \_
(/ /^^\ \)-'
 ""' '""
''',
'''
  .-"-.
 /|- -|\
{/(_0_)\}
 _/ ^^ \_
(/ /^^\ \)-'
 ""' '""
''',
]

[clips.happy]
frame_ms = 200
frames = [
'''
  .-"-.
 /|^^ ^^|\
{/(_0_)\}
 _/ ^1U^0 \_
(/ /^^\ \)-'
 ""' '""
''',
'''
  .-"-.
 /|^^ ^^|\
{/(_0_)\}
 _/ ^1U^0 \_
(/ /^^\ \)-,
 ""' '""
''',
]

[clips.sad]
frame_ms = 500
sequence = [0, 0, 0, 0, 0, 1]
frames = [
'''
  .-"-.
 /|^2;^0 ^2;^0|\
{/(_0_)\}
 _/ ^^ \_
(/ /^^\ \)
 ""' '""
''',
'''
  .-"-.
 /|- -|\
{/(_0_)\}
 _/ ^^ \_
(/ /^^\ \)
 ""' '""
''',
]

[clips.eat]
frame_ms = 300
sequence = [0, 1, 0, 1, 0, 1]
frames = [
'''
  .-"-.
 /|6 6|\
{/(_0_)\}
 _/ ^^ \_
(/ /^^\ \)-'
 ""' '""  ^3@
''',
'''
  .-"-.
 /|^^ ^^|\
{/(_0_)\}
 _/ ^1U^0 \_
(/ /^^\ \)-,
 ""' '""  ^3.:
''',
]

[clips.pet]
frame_ms = 300
sequence = [0, 1, 0, 1, 0, 1]
frames = [
'''
  .-"-.
 /|^^ ^^|\  ^1♥
{/(_0_)\}
 _/ ^1U^0 \_
(/ /^^\ \)-'
 ""' '""
''',
'''
  .-"-.   ^1♥
 /|^^ ^^|\
{/(_0_)\}
 _/ ^1U^0 \_
(/ /^^\ \)-,
 ""' '""
''',
]

[clips.play]
frame_ms = 250
sequence = [0, 1, 0, 1, 0, 1, 0, 1]
frames = [
'''
  .-"-.
 /|6 6|\
{/(_0_)\}
 _/ ^^ \_
(/ /^^\ \)-'
 ""' '""   ^2o
''',
'''
  .-"-.
 /|O O|\
{/(_0_)\}
 _/ ^1U^0 \_   ^2o
(/ /^^\ \)-,
 ""' '""
''',
]

[clips.sleep]
frame_ms = 700
frames = [
'''
  .-"-.  ^4z
 /|- -|\
{/(_0_)\}
 _/ ^^ \_
(/ /^^\ \)-'
 ""' '""
''',
'''
  .-"-.    ^4Z
 /|- -|\  ^4z
{/(_0_)\}
 _/ ^^ \_
(/ /^^\ \)-'
 ""' '""
''',
]
